### PR TITLE
Added test to reproduce bug where ROOT is added when combining two documents.

### PR DESCRIPTION
**Pull request by crdoconnor**
Hi, I've added a minimal case for a bug I ran across yesterday.

### CODE REVIEW

**Comment by durableOne** [comment]
Sorry for the delay. I was on  vacation. I'll take a look

**Comment by crdoconnor** [comment]
No worries. I actually thought it might have been intentional so no problems if you want to reject it.

**Comment by crdoconnor** [comment]
*thought after submitting the test that is.

**Comment by durableOne** [comment]
Please see https://github.com/durableOne/orgmunge/commit/f8976cb128703dba80b73215fd364bf5bcd9cfd1
I have corrected the code of the test case that adds headings from 2 trees to show you the correct way of doing that. All tests now passing.

**Comment by crdoconnor** [comment]
ah awesome, thanks

**Pull request merged**
